const productosInfo = [
  {
    id: 1,
    img: "img/productos/gloss-may.jpg",
    alt: "gloss-may",
    nombre: "Maybelline Gloss",
    precio: 8000,
    tono: "Tono: Pétalo",
    articulo: "gloss",
  },
  {
    id: 2,
    img: "img/productos/labial-velvet.png",
    alt: "labial velvet",
    nombre: "Labial HD velvet",
    precio: 15000,
    tono: "Tono: Rojo ésika",
    articulo: "labial",
  },
  {
    id: 3,
    img: "img/productos/matte.jpg",
    alt: "labial rimmel",
    nombre: "labial rimmel",
    precio: 13000,
    tono: "Tono: mauve bliss",
    articulo: "labial",
  },
  {
    id: 4,
    img: "img/productos/labial-rojo.png",
    alt: "labial sensat",
    nombre: "Maybelline Sensat",
    precio: 15000,
    tono: "Tono: Borgoña",
    articulo: "labial",
  },
  {
    id: 5,
    img: "img/productos/rojo-seductor.png",
    alt: "labial super stay",
    nombre: "Labial colorfix",
    precio: 20000,
    tono: "Tono: Rojo seductor",
    articulo: "labial",
  },
  {
    id: 6,
    img: "img/productos/rhode-gloss.png",
    alt: "gloss rhode",
    nombre: "Gloss Rhode",
    precio: 22000,
    tono: "Tono: Brillos",
    articulo: "gloss",
  },
  {
    id: 7,
    img: "img/productos/labial-nivea.jpg",
    alt: "labial nivea",
    nombre: "Nivea humectante",
    precio: 3000,
    tono: "Tono: Blackberry",
    articulo: "labial",
  },
  {
    id: 8,
    img: "img/productos/mascarilla-sandia.png",
    alt: "mascarilla sandia",
    nombre: "Mascarilla garnier",
    precio: 3100,
    tono: "Aroma: Sandia",
    articulo: "mascarilla",
  },
  {
    id: 9,
    img: "img/productos/mascarilla-coco.png",
    alt: "mascarilla coco ojos",
    nombre: "Mascarilla para ojos ",
    precio: 3000,
    tono: "Aroma: Coco",
    articulo: "mascarilla",
  },
];
